"""add lockout fields and vendor bank account encryption

Revision ID: 7bae789e7082
Revises: 39a4e8a09dcf
Create Date: 2026-09-30 12:53:54.523502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7bae789e7082'
down_revision: Union[str, None] = '39a4e8a09dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    )
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vendors', sa.Column('bank_account_enc', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'bank_account_enc')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
