"""initial schema

Revision ID: aa814cf60ddc
Revises: ec967035307f
Create Date: 2026-09-30 12:39:28.337466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'aa814cf60ddc'
down_revision: Union[str, None] = 'ec967035307f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_policies',
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('required_role', sa.String(length=30), nullable=False),
    sa.Column('steps', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_policies'))
    )
    op.create_table('items',
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('std_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('sku', name=op.f('uq_items_sku'))
    )
    op.create_index('ix_items_embedding', 'items', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('tolerance_policies',
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('qty_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price_abs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_abs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_abs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tolerance_policies'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('approval_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_enc', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_normalized', sa.String(length=300), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_days', sa.Integer(), nullable=True),
    sa.Column('risk_tier', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('code', name=op.f('uq_vendors_code'))
    )
    op.create_index('ix_vendors_embedding', 'vendors', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_vendors_name_normalized_trgm', 'vendors', ['name_normalized'], unique=False, postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.create_table('analytics_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('invoices_count', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('exceptions_by_type_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stp_count', sa.Integer(), nullable=False),
    sa.Column('savings_prevented', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discounts_captured', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discounts_missed', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_analytics_daily_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_daily')),
    sa.UniqueConstraint('date', 'vendor_id', 'category', name='uq_analytics_daily_grain')
    )
    op.create_index(op.f('ix_analytics_daily_date'), 'analytics_daily', ['date'], unique=False)
    op.create_table('audit_log',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('hash_prev', sa.String(length=64), nullable=True),
    sa.Column('hash_self', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('documents',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=True)
    op.create_table('payment_batches',
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('released_by', sa.UUID(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payment_batches_created_by_users')),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], name=op.f('fk_payment_batches_released_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_batches'))
    )
    op.create_table('purchase_orders',
    sa.Column('po_number', sa.String(length=30), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_purchase_orders_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('po_number', name=op.f('uq_purchase_orders_po_number'))
    )
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('grn_number', sa.String(length=30), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('received_by', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_goods_receipts_po_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipts')),
    sa.UniqueConstraint('grn_number', name=op.f('uq_goods_receipts_grn_number'))
    )
    op.create_index(op.f('ix_goods_receipts_po_id'), 'goods_receipts', ['po_id'], unique=False)
    op.create_table('invoices',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('freight', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('po_number_ref', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('dup_key', sa.String(length=300), nullable=True),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_invoices_document_id_documents')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_invoices_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('vendor_id', 'invoice_no', name='uq_invoices_vendor_invoice_no')
    )
    op.create_index(op.f('ix_invoices_document_id'), 'invoices', ['document_id'], unique=False)
    op.create_index(op.f('ix_invoices_dup_key'), 'invoices', ['dup_key'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qty_invoiced_cum', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_po_lines_item_id_items')),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_po_lines_po_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_lines'))
    )
    op.create_index(op.f('ix_po_lines_po_id'), 'po_lines', ['po_id'], unique=False)
    op.create_table('approvals',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_approvals_approver_id_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_approvals_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_invoice_id'), 'approvals', ['invoice_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.String(length=1000), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_exceptions_assigned_to_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_exceptions_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_exceptions_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exceptions'))
    )
    op.create_index(op.f('ix_exceptions_invoice_id'), 'exceptions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_exceptions_status'), 'exceptions', ['status'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('stage_path', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('errors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_extraction_runs_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_runs'))
    )
    op.create_index(op.f('ix_extraction_runs_invoice_id'), 'extraction_runs', ['invoice_id'], unique=False)
    op.create_table('gr_lines',
    sa.Column('grn_id', sa.UUID(), nullable=False),
    sa.Column('po_line_id', sa.UUID(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipts.id'], name=op.f('fk_gr_lines_grn_id_goods_receipts')),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], name=op.f('fk_gr_lines_po_line_id_po_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gr_lines'))
    )
    op.create_index(op.f('ix_gr_lines_grn_id'), 'gr_lines', ['grn_id'], unique=False)
    op.create_index(op.f('ix_gr_lines_po_line_id'), 'gr_lines', ['po_line_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bbox_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_lines_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines'))
    )
    op.create_index('ix_invoice_lines_embedding', 'invoice_lines', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_llm_usage_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index(op.f('ix_llm_usage_ts'), 'llm_usage', ['ts'], unique=False)
    op.create_table('match_results',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tolerance_policy_id', sa.UUID(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_match_results_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_match_results_po_id_purchase_orders')),
    sa.ForeignKeyConstraint(['tolerance_policy_id'], ['tolerance_policies.id'], name=op.f('fk_match_results_tolerance_policy_id_tolerance_policies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_results'))
    )
    op.create_index(op.f('ix_match_results_invoice_id'), 'match_results', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['payment_batches.id'], name=op.f('fk_payments_batch_id_payment_batches')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_scheduled_date'), 'payments', ['scheduled_date'], unique=False)
    op.create_table('match_line_results',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('invoice_line_id', sa.UUID(), nullable=True),
    sa.Column('po_line_id', sa.UUID(), nullable=True),
    sa.Column('qty_inv', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('qty_po', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('qty_recv', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('qty_prev_invoiced', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('price_inv', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('price_po', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('qty_var', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('price_var_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], name=op.f('fk_match_line_results_invoice_line_id_invoice_lines')),
    sa.ForeignKeyConstraint(['match_id'], ['match_results.id'], name=op.f('fk_match_line_results_match_id_match_results')),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], name=op.f('fk_match_line_results_po_line_id_po_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_line_results'))
    )
    op.create_index(op.f('ix_match_line_results_match_id'), 'match_line_results', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_line_results_match_id'), table_name='match_line_results')
    op.drop_table('match_line_results')
    op.drop_index(op.f('ix_payments_scheduled_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_match_results_invoice_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_llm_usage_ts'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_index('ix_invoice_lines_embedding', table_name='invoice_lines', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_gr_lines_po_line_id'), table_name='gr_lines')
    op.drop_index(op.f('ix_gr_lines_grn_id'), table_name='gr_lines')
    op.drop_table('gr_lines')
    op.drop_index(op.f('ix_extraction_runs_invoice_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_exceptions_status'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_invoice_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_approvals_invoice_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_po_lines_po_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_dup_key'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_goods_receipts_po_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('payment_batches')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_analytics_daily_date'), table_name='analytics_daily')
    op.drop_table('analytics_daily')
    op.drop_index('ix_vendors_name_normalized_trgm', table_name='vendors', postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.drop_index('ix_vendors_embedding', table_name='vendors', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tolerance_policies')
    op.drop_index('ix_items_embedding', table_name='items', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('items')
    op.drop_table('approval_policies')
    # ### end Alembic commands ###
